name: iOS Qt5 CI

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   tags:
  #     - '**'
  #   paths-ignore:
  #     - ".gitignore"
  #     - "README.md"
  #     # ignore CI for other platforms
  #     - ".github/FUNDING.yml"
  #     - ".github/actions/**"
  #     - ".github/workflows/Android-Qt5.yml"
  #     - ".github/workflows/Android-Qt6.yml"
  #     - ".github/workflows/iOS-Qt6.yml"
  #     - ".github/workflows/Linux-Qt5.yml"
  #     - ".github/workflows/Linux-Qt6.yml"
  #     - ".github/workflows/macOS-Qt5.yml"
  #     - ".github/workflows/macOS-Qt6.yml"
  #     - ".github/workflows/Windows-Qt5.yml"
  #     - ".github/workflows/Windows-Qt6.yml"

  # pull_request:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - ".gitignore"
  #     - "README.md"
  #     # ignore CI for other platforms
  #     - ".github/FUNDING.yml"
  #     - ".github/actions/**"
  #     - ".github/workflows/Android-Qt5.yml"
  #     - ".github/workflows/Android-Qt6.yml"
  #     - ".github/workflows/iOS-Qt6.yml"
  #     - ".github/workflows/Linux-Qt5.yml"
  #     - ".github/workflows/Linux-Qt6.yml"
  #     - ".github/workflows/macOS-Qt5.yml"
  #     - ".github/workflows/macOS-Qt6.yml"
  #     - ".github/workflows/Windows-Qt5.yml"
  #     - ".github/workflows/Windows-Qt6.yml"

concurrency:
  # cancel jobs on PRs only
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  QT_VERSION: 5.15.2

jobs:
  build-core:
    name: "Build maplibre-native"
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: source
          submodules: recursive
          fetch-depth: 0

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Download Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: ==3.0.*
          version: ${{ env.QT_VERSION }}
          target: ios

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: iOS_maplibre-native_legacy
          append-timestamp: false

      - name: Use custom version of ccache
        run: |
          sed -i.bak -e 's/ccache\/ccache\.git/ntadej\/ccache.git/' -e 's/master/xarch/' /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ccache.rb
          brew unlink ccache
          brew install ccache --HEAD

      - name: Build maplibre-native
        run: |
          export CCACHE_LOGFILE=../ccache.log
          mkdir build && cd build
          cmake ../source/vendor/maplibre-native/ \
            -G"Ninja Multi-Config" \
            -DCMAKE_CONFIGURATION_TYPES="Release;Debug" \
            -DCMAKE_C_COMPILER_LAUNCHER="ccache" \
            -DCMAKE_CXX_COMPILER_LAUNCHER="ccache" \
            -DCMAKE_FIND_ROOT_PATH="$Qt5_Dir" \
            -DCMAKE_INSTALL_PREFIX="${Qt5_Dir//\/bin/}" \
            -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
            -DCMAKE_PREFIX_PATH="$Qt5_Dir" \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DMLN_WITH_QT=ON \
            -DMLN_QT_LIBRARY_ONLY=ON
          ninja
          DESTDIR=../install ninja install

      - name: Upload ccache.log
        uses: actions/upload-artifact@v3
        with:
          name: ccache_iOS
          path: ccache.log

      - name: Create artifacts
        run: |
          pushd install/Users/runner/work/maplibre-native-qt
          tar cjvf ../../../../../QMapLibreGL_iOS.tar.bz2 Qt
          popd

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: maplibre-native_iOS
          path: QMapLibreGL_iOS.tar.bz2

  build-plugin:
    name: "Build qt-geoservices-maplibre-gl"
    runs-on: macos-12
    needs: build-core

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: source
          fetch-depth: 0

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Download Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: ==3.0.*
          version: ${{ env.QT_VERSION }}
          target: ios

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: iOS_qt-geoservices-maplibre-gl_legacy
          append-timestamp: false

      - name: Use custom version of ccache
        run: |
          sed -i.bak -e 's/ccache\/ccache\.git/ntadej\/ccache.git/' -e 's/master/xarch/' /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ccache.rb
          brew unlink ccache
          brew install ccache --HEAD

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: maplibre-native_iOS

      - name: Build qt-geoservices-maplibre-gl
        run: |
          tar xvf QMapLibreGL_iOS.tar.bz2 -C ..
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          mkdir build && cd build
          qmake ../source/
          make -j2
          INSTALL_ROOT=../install make install

      - name: Create artifacts
        run: |
          pushd install/Users/runner/work/maplibre-native-qt
          tar xvf ../../../../../QMapLibreGL_iOS.tar.bz2
          tar cjvf ../../../../../qt-geoservices-maplibre-gl_iOS.tar.bz2 Qt
          popd

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: qt-geoservices-maplibre-gl_iOS
          path: qt-geoservices-maplibre-gl_iOS.tar.bz2

  release:
    name: "Release qt-geoservices-maplibre-gl"
    if: github.ref_type == 'tag'
    runs-on: macos-12
    needs: build-plugin
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: qt-geoservices-maplibre-gl_iOS

      - name: Make tarball
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          mv qt-geoservices-maplibre-gl_iOS.tar.bz2 qt-geoservices-maplibre-gl_${TAG_NAME}_Qt${QT_VERSION}_iOS.tar.bz2

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: qt-geoservices-maplibre-gl_${{ github.ref_name }}_Qt${{ env.QT_VERSION }}_iOS.tar.bz2
          allowUpdates: true
          draft: true
